name: ci-inner
on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true
      upload-packages:
        type: boolean
        required: false
        default: false
permissions: read-all
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            sdk: "10.0.101"
          - os: ubuntu-24.04
            sdk: "8.0.416"
          - os: ubuntu-24.04
            sdk: "9.0.308"
          - os: ubuntu-24.04
            sdk: "10.0.101"
          - os: ubuntu-24.04-arm
            sdk: "8.0.416"
          - os: ubuntu-24.04-arm
            sdk: "9.0.308"
          - os: ubuntu-24.04-arm
            sdk: "10.0.101"
            upload-packages: true
          - os: windows-2025
            sdk: "10.0.101"
          - os: windows-11-arm
            sdk: "10.0.101"
    name: ${{ matrix.os }}-sdk-${{ matrix.sdk }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-dotnet@v5.0.1
        with:
          dotnet-version: |
            ${{ matrix.sdk }}
            10.0.101
      - run: dotnet --info
      - run: git --version
      - uses: actions/checkout@v6.0.1
        with:
          persist-credentials: false
      - env:
          BUILD_METADATA: build.${{ github.run_id }}.${{ github.run_attempt}}
          CI_NUMBER: ${{ github.run_number }}
          MINVER_VERSION: ${{ vars.MINVER_VERSION }}
          MINVER_SDK: ${{ matrix.sdk }}
          TARGET: ${{ inputs.target }}
        run: ./build "$TARGET" --verbose
        shell: bash
      - if: ${{ inputs.upload-packages && matrix.upload-packages }}
        uses: actions/upload-artifact@v6.0.0
        with:
          name: NuGet packages
          path: ./**/*.nupkg
