name: ci-test-packages
on:
  push:
    branches: [main, release-*]
  pull_request:
  workflow_dispatch:
permissions: read-all
env:
  DOTNET_NOLOGO: true
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            sdk: "10.0.103"
          - os: ubuntu-24.04
            sdk: "8.0.418"
          - os: ubuntu-24.04
            sdk: "9.0.311"
          - os: ubuntu-24.04
            sdk: "10.0.103"
          - os: ubuntu-24.04-arm
            sdk: "8.0.418"
          - os: ubuntu-24.04-arm
            sdk: "9.0.311"
          - os: ubuntu-24.04-arm
            sdk: "10.0.103"
            upload-packages: true
          - os: windows-2025
            sdk: "10.0.103"
          - os: windows-11-arm
            sdk: "10.0.103"
    name: ${{ matrix.os }}-sdk-${{ matrix.sdk }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
        with:
          dotnet-version: |
            ${{ matrix.sdk }}
            10.0.103
      - run: dotnet --info
      - run: git --version
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - env:
          MINVER_SDK: ${{ matrix.sdk }}
        run: ./build test-packages
