name: ci-test-packages
on:
  push:
    branches: [main, release-*]
  pull_request:
  workflow_dispatch:
permissions: read-all
env:
  DOTNET_NOLOGO: true
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            sdk: "10.0.102"
          - os: ubuntu-24.04
            sdk: "8.0.417"
          - os: ubuntu-24.04
            sdk: "9.0.310"
          - os: ubuntu-24.04
            sdk: "10.0.102"
          - os: ubuntu-24.04-arm
            sdk: "8.0.417"
          - os: ubuntu-24.04-arm
            sdk: "9.0.310"
          - os: ubuntu-24.04-arm
            sdk: "10.0.102"
            upload-packages: true
          - os: windows-2025
            sdk: "10.0.102"
          - os: windows-11-arm
            sdk: "10.0.102"
    name: ${{ matrix.os }}-sdk-${{ matrix.sdk }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-dotnet@v5.0.1
        with:
          dotnet-version: |
            ${{ matrix.sdk }}
            10.0.102
      - run: dotnet --info
      - run: git --version
      - uses: actions/checkout@v6.0.1
        with:
          persist-credentials: false
      - env:
          MINVER_SDK: ${{ matrix.sdk }}
        run: ./build test-packages
